from __future__ import annotations

import os

SECRET_KEY = os.environ["SUPERSET_SECRET_KEY"]

CACHE_CONFIG = {
    "CACHE_TYPE": "SimpleCache",
    "CACHE_DEFAULT_TIMEOUT": 300,
}

DATA_CACHE_CONFIG = CACHE_CONFIG.copy()
FILTER_STATE_CACHE_CONFIG = CACHE_CONFIG.copy()
EXPLORE_FORM_DATA_CACHE_CONFIG = CACHE_CONFIG.copy()

FEATURE_FLAGS = {
    "THUMBNAILS": False,
    "ENABLE_DASHBOARD_SCREENSHOT_ENDPOINTS": False,
    "ENABLE_DASHBOARD_DOWNLOAD_WEBDRIVER_SCREENSHOT": False,
    "PLAYWRIGHT_REPORTS_AND_THUMBNAILS": False,
    "ALERT_REPORTS": False,
    "ALERT_REPORT_TABS": False,
    "ALERT_REPORT_SLACK_V2": False,
    "ALERTS_ATTACH_REPORTS": False,
    "GLOBAL_ASYNC_QUERIES": False,
    "SQLLAB_FORCE_RUN_ASYNC": False,
}

CELERY_CONFIG = None
RESULTS_BACKEND = None

BABEL_DEFAULT_TIMEZONE = "UTC"
