apiVersion: 1

contactPoints:
  - orgId: 1
    name: Urban Green Ops
    receivers:
      - uid: urbangreen_ops_email
        type: email
        settings:
          addresses: ops@urbangreen.local

policies:
  - orgId: 1
    receiver: Urban Green Ops
    group_by: [grafana_folder, alertname]
