CREATE SCHEMA IF NOT EXISTS urbangreen;

CREATE TABLE urbangreen.users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
    updated_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
);

CREATE TABLE urbangreen.roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE,
    description VARCHAR NOT NULL,
    created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
    updated_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
);

CREATE TABLE urbangreen.farm_infrastructure_types (
    farm_infrastructure_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE,
    description VARCHAR NOT NULL,
   created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
    updated_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
);

CREATE TABLE urbangreen.growing_system_types (
    growing_system_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE,
    description VARCHAR NOT NULL,
    created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
    updated_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
);

CREATE TYPE urbangreen.farm_status AS ENUM(
     'ACTIVE',
     'MAINTENANCE',
     'INACTIVE'
);

CREATE TYPE urbangreen.sensor_status AS ENUM(
    'ACTIVE',
    'OFFLINE',
    'MAINTENANCE'
);

CREATE TABLE urbangreen.farms (
    farm_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    farm_infrastructure_type_id BIGINT NOT NULL REFERENCES urbangreen.farm_infrastructure_types(farm_infrastructure_type_id),
    growing_system_type_id BIGINT NOT NULL REFERENCES urbangreen.growing_system_types(growing_system_type_id),
    name VARCHAR NOT NULL UNIQUE,
    city VARCHAR NOT NULL,
    size_m2 DECIMAL(10,3) NOT NULL CHECK (size_m2 >= 0),
    status urbangreen.farm_status NOT NULL,
    growing_beds_count INT NOT NULL CHECK (growing_beds_count >= 0),
    created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
    updated_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
);

CREATE TABLE urbangreen.user_roles (
    user_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES urbangreen.users(user_id),
    role_id BIGINT NOT NULL REFERENCES urbangreen.roles(role_id),
    farm_id BIGINT REFERENCES urbangreen.farms(farm_id),
    created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
    updated_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
);

CREATE TABLE urbangreen.sensor_types (
    sensor_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE,
    unit VARCHAR NOT NULL,
    description VARCHAR,
    optimal_min DECIMAL(10,3),
    optimal_max DECIMAL(10,3),
    created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
    updated_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
);

CREATE TABLE urbangreen.sensors (
    sensor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id BIGINT NOT NULL REFERENCES urbangreen.farms(farm_id),
    sensor_type_id BIGINT NOT NULL REFERENCES urbangreen.sensor_types(sensor_type_id),
    serial_number VARCHAR NOT NULL UNIQUE,
    status urbangreen.sensor_status NOT NULL,
    installed_at BIGINT,
    created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
    updated_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
);

CREATE TABLE urbangreen.crop_categories (
    crop_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE,
    description VARCHAR,
    created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
    updated_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
);

CREATE TABLE urbangreen.crops (
    crop_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_category_id BIGINT NOT NULL REFERENCES urbangreen.crop_categories(crop_category_id),
    name VARCHAR NOT NULL UNIQUE,
    description VARCHAR,
    created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
    updated_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
);

CREATE TABLE urbangreen.quality_grades (
    quality_grade_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL,
    description VARCHAR,
    created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
    updated_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
);

CREATE TABLE urbangreen.farm_crops (
    farm_crop_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id BIGINT NOT NULL REFERENCES urbangreen.farms(farm_id),
    crop_id BIGINT NOT NULL REFERENCES urbangreen.crops(crop_id),
    started_at BIGINT NOT NULL,
    ended_at BIGINT,
    created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
    updated_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),

    CONSTRAINT uq_farm_crops_farm_crop_started_at
        UNIQUE (farm_id, crop_id, started_at),

    CONSTRAINT chk_farm_crops_date_range
        CHECK (ended_at IS NULL OR ended_at >= started_at)
);

CREATE TABLE urbangreen.harvests (
    harvest_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id BIGINT NOT NULL REFERENCES urbangreen.farms(farm_id),
    crop_id BIGINT NOT NULL REFERENCES urbangreen.crops(crop_id),
    quality_grade_id BIGINT NOT NULL REFERENCES urbangreen.quality_grades(quality_grade_id),
    weight_kg DECIMAL(10,3) NOT NULL CHECK (weight_kg >= 0),
    created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
    updated_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
);


CREATE INDEX idx_harvests_farm_id
ON urbangreen.harvests(farm_id);

CREATE INDEX idx_harvests_crop_id
ON urbangreen.harvests(crop_id);

CREATE INDEX idx_harvests_created_at
ON urbangreen.harvests(created_at);

CREATE INDEX idx_harvests_updated_at
ON urbangreen.harvests(updated_at);

CREATE INDEX idx_harvests_farm_created_at
ON urbangreen.harvests(farm_id, created_at);
