FROM apache/airflow:3.1.1-python3.10

COPY requirements.txt /requirements.txt

RUN pip install --no-cache-dir \
    "apache-airflow==${AIRFLOW_VERSION}" \
    -r /requirements.txt \
    -c "${HOME}/constraints.txt"