apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://urbangreen-prometheus:9090
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://urbangreen-loki:${LOKI_PORT:-3100}
    isDefault: false
    editable: false