global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    cluster: urbangreen

scrape_configs:
  - job_name: urbangreen-api
    static_configs:
      - targets:
          - urbangreen-api:8000

  - job_name: urbangreen-mcp
    static_configs:
      - targets:
          - urbangreen-mcp:8001

  - job_name: urbangreen-minio
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets:
          - urbangreen-minio:9000

  - job_name: urbangreen-clickhouse
    static_configs:
      - targets:
          - urbangreen-clickhouse:9363

  - job_name: urbangreen-spark-master
    metrics_path: /metrics/master/prometheus
    static_configs:
      - targets:
          - urbangreen-spark-master:8090

  - job_name: urbangreen-spark-applications
    metrics_path: /metrics/applications/prometheus
    static_configs:
      - targets:
          - urbangreen-spark-master:8090

  - job_name: urbangreen-spark-worker-1
    metrics_path: /metrics/prometheus
    static_configs:
      - targets:
          - urbangreen-spark-worker-1:8081

  - job_name: urbangreen-spark-worker-2
    metrics_path: /metrics/prometheus
    static_configs:
      - targets:
          - urbangreen-spark-worker-2:8081

  - job_name: urbangreen-spark-streaming
    metrics_path: /metrics/prometheus
    static_configs:
      - targets:
          - urbangreen-spark-streaming:4050

  - job_name: urbangreen-kafka-exporter
    static_configs:
      - targets:
          - urbangreen-kafka-exporter:9308
